### ISSUE TITLE
エラー表示がおかしい

### ISSUE THREAD

**Issue by RearAlice** [nicovrc-net/nico-proxy_forVRC#7]
*サイトに問い合わせあったものを転送しています。

以下の内容が発生している。

- abema のエラー表示がbilibliになってる
- bilibliのエラー表示がツイキャスになってる 
etc...

**Comment by kanasaki15** [comment]
再現なし(ログにもない)

**Comment by kanasaki15** [comment]
Cloudflare側のキャッシュのせいだった　おしまい
